### ISSUE TITLE
Fritzcall will "telephone book" nicht importieren

### ISSUE THREAD

**Issue by DjoeC** [DrMichael/FritzCall#10]
Mein Fritzcall will dass telefonbuch nicht aus dem Fritz (5590 oder 7583, sowol vorherige als letzte firmware) nicht lesen.  Fritzbox steht auf English, telefonbuch heisst: "telephone book".  Wenn ich ein kopie mache mit name "a" und dass importiere gibts kein problem ABER die beide telefonbuecher bleiben nicht automatisch synchron.

Kann nicht finden wesshalb dieses falsch geht, vielleicht weil "telephone book" ein space im namen hat?

**Comment by DrMichael** [comment]
Das kann gut sein, nie getestet. Eventuell ist auch Englisch das Problem?
Im Zweifel Logging auf DEBUG und mir das Fritzdebug.log per PN schicken.

(Neueste Version drauf, nehme ich an?)

**Comment by DjoeC** [comment]
Alles neueste versionen.  Wird kommendes wochenende mal debug machen & ueber PN zuschicken.
