### ISSUE TITLE
Fritzcall stört den VTI sat>ip client

### ISSUE THREAD

**Issue by Conan179** [DrMichael/FritzCall#2]
Hi, ich hab ein problem und zwar wen Fritzcall einnstalliert und eingerichtet habe, kann ich die sat>ip funktion des vti image nicht mehr nutzten, die verbinund wird ständig getrennt, die fritzbox sagt immer im log:
"Die Anwendung mit der IP-Adresse 192.168.1.3 reagiert nicht. Die TV-Übertragung wurde gestoppt."
Es tritt bei allen sendern auf. 
Ausschliesen kann ich ein fritzbox problem, in meinem netzwerk sind eine 6590 (sat>ip server. mesh repeater) und eine oem 6591 (Vodafone) die Als mesh master, internet,Telefon macht.
VTI image 15 und ein älteres VTI 14 image zeigen das gleiche verhalten (unteerschiedliche fritzcall versionen eine von 2018 und 2021)
Momentan ist diese Version innstalliert https://github.com/DrMichael/FritzCall/releases/tag/rev1594
könnt ihr mir bei diesem Problem helfen?

**Comment by Conan179** [comment]
Lösung wurde gefunden, wird nicht öffentlich gemacht.

**Comment by dhwz** [comment]
?
